### PR TITLE
chore: rename class to be more mew wallet specific

### PR DESCRIPTION
**Pull request by gamalielhere**

### CODE REVIEW

**Comment by bdhaccess94** [comment]
<template>
  <div>
    <p>
      <router-link to="/home">Go to Home</router-link>
    </p>
    <button @click="setup">Show web3 modal popup</button>
    <br />
    <br />
    <br />
    <p>
      <a
        href="https://github.com/MyEtherWallet/MEWconnect-web-client/blob/mewconnect-demo/src/web3Modal/web3Modal.vue"
        target="_blank"
        >Code for this example</a
      >
    </p>
  </div>
</template>

<script>
/* eslint-disable */
import Web3 from 'web3';
import Web3Modal from 'web3modal';
// @ts-ignore
import MewConnect from '@myetherwallet/mewconnect-web-client';
export default {
  name: 'web3Modal',
  title: 'web3 Modal Example',
  data () {
    return {
      web3: {}
    };
  },
  mounted () {
  },
  methods: {
    async setup () {
      const providerOptions = {
        mewconnect: {
          package: MewConnect,
          options: {
            infuraId: process.env.REACT_APP_INFURA_ID || '859569f6decc4446a5da1bb680e7e9cf'
          }
        },
      };
      const web3Modal = new Web3Modal({
        network: 'mainnet', // optional
        cacheProvider: true, // optional
        providerOptions // required
      });
      const provider = await web3Modal.connect();
      this.web3 = new Web3(provider);
    }
  }
};
</script>

<style lang="scss">
  #app {
    font-family: 'Avenir', Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-align: center;
    color: #2c3e50;
    margin-top: 60px;
  }
  ul {
    list-style-type: none;
    li {
      text-align: center;
    }
  }
</style>

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @bdhaccess94)

**Comment by bapisit** [comment]
Tell more

**Comment by joeleonjr** [comment]
@bdhaccess94 's infura token is in the comment from Sept 25, 2021. They should rotate that key to ensure no one uses it.

**Comment by bapisit** [comment]
Do you mean private key

**Comment by bapisit** [comment]
Ok I get muun app get me API key

**Pull request merged**
